groups: 
- name: test
  rules:
  - alert: service_down
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Prometheus target missing (instance {{ $labels.instance }})"
      description: "A Prometheus target has disappeared. An exporter might be crashed. VALUE = {{ $value }}  LABELS: {{ $labels }}"
  - alert: high_load
    expr: sum(rate(cpu_usage_seconds_total[5m])) by (instance) > 0.9
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "High CPU usage detected on {{ $labels.instance }}"
      description: "CPU usage is above 90% for more than 5 minutes."