{
 "title": "my_dashboard_1",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RAM Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{job=\"node\"} - node_memory_MemFree_bytes{job=\"node\"}) / (node_memory_MemTotal_bytes{job=\"node\"} / 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cpu_load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - avg by(instance)(irate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_load1{job=\"node\"} ",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load5{job=\"node\"} ",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load15{job=\"node\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "freeHDD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(\r\n  node_filesystem_size_bytes{job='node',mountpoint=\"/\", fstype!~\"tmpfs|overlay|rootfs\"}\r\n) by (instance)\r\n/\r\n1024/1024/1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(node_filesystem_free_bytes{job='node',mountpoint=\"/\", fstype!~\"tmpfs|overlay|rootfs\"})by(instance)/1024/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}