global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prome
    scrape_interval: 5s
    static_configs:
    - targets: 
      - nodeexporter:9100

  - job_name: node
    scrape_interval: 5s
    static_configs:
    - targets: 
      - 192.168.62.17:9100

rule_files:
  - '/etc/prometheus/alert.rules.yml'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

    